services:
  db:
   image: postgres:14
   container_name: prod_postgres
   restart: unless-stopped
   environment:
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTRGES_DB: ${POSTGRES_DB}
   volumes:
    - pgdata:/var/lib/postgresql/data
    - ./postgres-init:/docker-entrypoint-initdb.d
   networks:
    - appnet

  redis:
    image: redis:7
    container_name: prod_redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
     REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
     - appnet    
  
  web:
    build: 
     context: .
     dockerfile: Dockerfile
    container_name: prod_aj_web
    restart: unless-stopped
    depends_on:
     - db
     - redis
    ports:
     - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}  
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      NODE_ENV: ${NODE_ENV}
      REDIS_URL: ${REDIS_URL}
      MAILER_LITE_API_KEY: ${MAILER_LITE_API_KEY}
    networks:
     - appnet


volumes:
 pgdata:      

networks:
  appnet: