
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  
    environment:
      DATABASE_URL: ${DATABASE_URL}  
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      NODE_ENV: ${NODE_ENV}
      REDIS_URL: ${REDIS_URL}
      MAILER_LITE_API_KEY: ${MAILER_LITE_API_KEY}
    volumes:
      - .:/app  
    networks:
      - nextjs-network


networks:
  nextjs-network:
    driver: bridge
