import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
const montesrrat = Montserrat({
  variable: '--font-monterrest',
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Alicia Bee Coaches Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montesrrat.variable}  antialiased bg-[#fff0f5]`}
      >

          {children}
    
      </body>
    </html>
  );
}