
import type { Metadata } from "next";
import Footer from "@/components/common/Footer";
import Navbar from "@/components/common/Navbar";
import Layout from "@/components/common/Layout";
import ArticlesPage from '@/pages/ArticlePage';
export const metadata: Metadata = {
    title: "Alicia Bee Coaches- Article Page",
    description: "Generated by create next app",
  };
const page = () => {
  return (
  <>
  <Navbar/>
  <Layout>
    <ArticlesPage/>
  </Layout>
  <Footer/>
  </>
  )
}

export default page